name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run hadolint
        uses: "docker://cdssnc/docker-lint-github-action"
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Registry
      run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
    - name: Build base Image
      run: |
        cd base
        make build
        make push
    - name: Build php images
      run: |
        cd php
        make build
        make push
    - name: Build apache image
      run: |
        cd apache
        make build
        make push

